CREATE TABLE IF NOT EXISTS ranp44_pe4_daily_staging (
    production_date DATE NOT NULL,
    well TEXT NOT NULL,
    entity TEXT,
    mpfm_tag TEXT,
    source_name TEXT NOT NULL,
    source_file TEXT,
    source_row INTEGER,
    granularity TEXT,
    usar BOOLEAN DEFAULT TRUE,
    status_dados TEXT,
    gvf_avg_pct DOUBLE PRECISION,
    gvf_min_pct DOUBLE PRECISION,
    gvf_max_pct DOUBLE PRECISION,
    salinidade_avg DOUBLE PRECISION,
    bsw_avg_pct DOUBLE PRECISION,
    pressao_min_bar DOUBLE PRECISION,
    pressao_max_bar DOUBLE PRECISION,
    temperatura_min_c DOUBLE PRECISION,
    temperatura_max_c DOUBLE PRECISION,
    massa_oleo_mpfm_t DOUBLE PRECISION,
    massa_gas_mpfm_t DOUBLE PRECISION,
    massa_agua_mpfm_t DOUBLE PRECISION,
    massa_oleo_ref_t DOUBLE PRECISION,
    massa_gas_ref_t DOUBLE PRECISION,
    massa_agua_ref_t DOUBLE PRECISION,
    volume_oleo_mpfm_sm3 DOUBLE PRECISION,
    volume_gas_mpfm_ksm3 DOUBLE PRECISION,
    volume_agua_mpfm_m3 DOUBLE PRECISION,
    xml042_ref TEXT,
    quality_json JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (production_date, well, source_name)
);

CREATE VIEW IF NOT EXISTS ranp44_pe4_daily_final AS
SELECT
    production_date,
    well,
    mpfm_tag,
    bool_or(usar) AS usar,
    max(status_dados) AS status_dados,
    avg(gvf_avg_pct) AS gvf_avg_pct,
    min(gvf_min_pct) AS gvf_min_pct,
    max(gvf_max_pct) AS gvf_max_pct,
    avg(salinidade_avg) AS salinidade_avg,
    avg(bsw_avg_pct) AS bsw_avg_pct,
    min(pressao_min_bar) AS pressao_min_bar,
    max(pressao_max_bar) AS pressao_max_bar,
    min(temperatura_min_c) AS temperatura_min_c,
    max(temperatura_max_c) AS temperatura_max_c,
    sum(massa_oleo_mpfm_t) AS massa_oleo_mpfm_t,
    sum(massa_gas_mpfm_t) AS massa_gas_mpfm_t,
    sum(massa_agua_mpfm_t) AS massa_agua_mpfm_t,
    sum(massa_oleo_ref_t) AS massa_oleo_ref_t,
    sum(massa_gas_ref_t) AS massa_gas_ref_t,
    sum(massa_agua_ref_t) AS massa_agua_ref_t,
    string_agg(DISTINCT source_file, '; ') AS source_files,
    string_agg(DISTINCT xml042_ref, '; ') AS xml042_refs
FROM ranp44_pe4_daily_staging
WHERE well = 'PE_4'
GROUP BY production_date, well, mpfm_tag;
